# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Feb 12 15:04:38 2021
# ------------------------------------------------

package:
  name: shapely
  version: 1.7.1
source:
  sha256: 1641724c1055459a7e2b8bbe47ba25bdc89554582e62aec23cb3f3ca25f9b129
  url: https://pypi.io/packages/source/S/Shapely/Shapely-1.7.1.tar.gz
build:
  number: '4'
  string: py38h4fc1155_4
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 hc3fd857_29
    - gcc_impl_linux-64 9.3.0 h70c0ae5_18
    - gcc_linux-64 9.3.0 h7247604_29
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_18
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - sysroot_linux-64 2.12 h77966d4_13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py38h578d9bd_1
    - cython 0.29.21 py38h709712a_2
    - geos 3.9.1 h9c3ff4c_0
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libblas 3.9.0 8_openblas
    - libcblas 3.9.0 8_openblas
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgfortran-ng 9.3.0 hff62375_18
    - libgfortran5 9.3.0 hff62375_18
    - libgomp 9.3.0 h2828fa1_18
    - liblapack 3.9.0 8_openblas
    - libopenblas 0.3.12 pthreads_h4812303_1
    - libstdcxx-ng 9.3.0 h6de172a_18
    - ncurses 6.2 h58526e2_4
    - numpy 1.16.6 py38h18fd61f_0
    - openssl 1.1.1i h7f98852_0
    - pip 21.0.1 pyhd8ed1ab_0
    - python 3.8.6 hffdb5ce_5_cpython
    - python_abi 3.8 1_cp38
    - readline 8.0 he28a2e2_2
    - setuptools 49.6.0 py38h578d9bd_3
    - sqlite 3.34.0 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - geos >=3.9.1,<3.9.2.0a0
    - libgcc-ng >=9.3.0
    - numpy >=1.16.6,<2.0a0
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
test:
  imports:
    - shapely
    - shapely.algorithms
    - shapely.examples
    - shapely.geometry
    - shapely.geos
  requires:
    - pytest
  source_files:
    - tests
about:
  home: https://github.com/Toblerity/Shapely
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package for manipulation and analysis of geometric objects in the
    Cartesian plane
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jorisvandenbossche
    - ocefpaf
    - pelson
    - phobson
    - xylar
