# This file created by conda-build 3.20.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Oct 16 16:41:00 2020
# ------------------------------------------------

package:
    name: olefile
    version: '0.46'
source:
    sha256: 133b031eaf8fd2c9399b78b8bc5b8fcbe4c31e85295749bb17a87cba8f3c3964
    url: https://pypi.io/packages/source/o/olefile/olefile-0.46.zip
build:
    noarch: python
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/olefile_1602866521163/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
        -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
    string: pyh9f0ad1d_1
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.6.20 hecda079_0
        - certifi 2020.6.20 py36h9880bd3_2
        - ld_impl_linux-64 2.35 h769bd43_9
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 he1b5a44_2
        - openssl 1.1.1h h516909a_0
        - pip 20.2.3 py_0
        - python 3.6.11 h4d41432_2_cpython
        - python_abi 3.6 1_cp36m
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py36h9880bd3_2
        - sqlite 3.33.0 h4cf870e_1
        - tk 8.6.10 hed695b0_1
        - wheel 0.35.1 pyh9f0ad1d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - python
test:
    imports:
        - olefile
about:
    dev_url: https://github.com/decalage2/olefile
    home: http://www.decalage.info/python/olefileio
    license: BSD-2-Clause
    license_family: BSD
    license_file: LICENSE.txt
    summary: 'Python package to parse, read and write Microsoft OLE2 files (Structured
        Storage or Compound Document, Microsoft Office) - Improved version of the
        OleFileIO module from PIL, the Python Image Library.

        '
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - decarlof
        - dgursoy
        - ericdill
        - licode
        - ocefpaf
        - ravescovi
        - tacaswell
