# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Mar  4 22:01:34 2021
# ------------------------------------------------

package:
  name: cartopy
  version: 0.18.0
source:
  patches:
    - backport-1565.patch
  sha256: 7ffa317e8f8011e0d965a3ef1179e57a049f77019867ed677d49dcc5c0744434
  url: https://pypi.io/packages/source/C/Cartopy/Cartopy-0.18.0.tar.gz
build:
  error_overlinking: true
  number: '13'
  string: py38hab71064_13
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - gcc_impl_linux-64 9.3.0 h70c0ae5_18
    - gcc_linux-64 9.3.0 hf25ea35_30
    - gxx_impl_linux-64 9.3.0 hd87eabc_18
    - gxx_linux-64 9.3.0 h3fbe746_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_18
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-devel_linux-64 9.3.0 hb016644_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - sysroot_linux-64 2.12 h77966d4_13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - c-ares 1.17.1 h36c2ea0_0
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py38h578d9bd_1
    - cython 0.29.22 py38h709712a_0
    - geos 3.9.1 h9c3ff4c_2
    - jpeg 9d h36c2ea0_0
    - krb5 1.17.2 h926e7f8_0
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libblas 3.9.0 8_openblas
    - libcblas 3.9.0 8_openblas
    - libcurl 7.71.1 hcdd3856_8
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgfortran-ng 9.3.0 hff62375_18
    - libgfortran5 9.3.0 hff62375_18
    - libgomp 9.3.0 h2828fa1_18
    - liblapack 3.9.0 8_openblas
    - libnghttp2 1.43.0 h812cca2_0
    - libopenblas 0.3.12 pthreads_h4812303_1
    - libssh2 1.9.0 hab1572f_5
    - libstdcxx-ng 9.3.0 h6de172a_18
    - libtiff 4.2.0 hdc55705_0
    - libwebp-base 1.2.0 h7f98852_0
    - lz4-c 1.9.3 h9c3ff4c_0
    - ncurses 6.2 h58526e2_4
    - numpy 1.16.6 py38h18fd61f_0
    - openssl 1.1.1j h7f98852_0
    - pip 21.0.1 pyhd8ed1ab_0
    - proj 7.2.0 h277dcde_2
    - python 3.8.8 hffdb5ce_0_cpython
    - python_abi 3.8 1_cp38
    - readline 8.0 he28a2e2_2
    - setuptools 49.6.0 py38h578d9bd_3
    - sqlite 3.34.0 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
    - zstd 1.4.9 ha95c52a_0
  run:
    - geos >=3.9.1,<3.9.2.0a0
    - libgcc-ng >=9.3.0
    - libstdcxx-ng >=9.3.0
    - matplotlib-base >=1.5.1
    - numpy >=1.16.6,<2.0a0
    - proj >=7.2.0,<7.2.1.0a0
    - pyshp >=1.1.4
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - scipy >=0.10
    - shapely >=1.5.6
    - six >=1.3.0
test:
  commands:
    - python -c "import cartopy.crs as ccrs; import matplotlib.pyplot as plt; ax =
      plt.axes(projection=ccrs.PlateCarree())"
  imports:
    - cartopy
    - cartopy.crs
    - cartopy.mpl.geoaxes
about:
  dev_url: https://github.com/SciTools/cartopy
  doc_url: https://scitools.org.uk/cartopy/docs/latest/
  home: http://scitools.org.uk/cartopy
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: A library providing cartographic tools for python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dopplershift
    - marqh
    - ocefpaf
    - pelson
    - xylar
