# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Mar 17 15:04:25 2021
# ------------------------------------------------

package:
  name: libwebp-base
  version: 1.2.0
source:
  sha256: 2fc8bbde9f97f2ab403c0224fb9ca62b2e6852cbc519e91ceaa7c153ffd88a0c
  url: http://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.2.0.tar.gz
build:
  number: '2'
  run_exports:
    - libwebp-base
  string: h7f98852_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - gcc_impl_linux-64 9.3.0 h70c0ae5_18
    - gcc_linux-64 9.3.0 hf25ea35_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_18
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - libtool 2.4.6 h58526e2_1007
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 h77966d4_13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
  run:
    - libgcc-ng >=9.3.0
  run_constrained:
    - libwebp 1.2.0
test:
  commands:
    - test -f $PREFIX/lib/libwebp.a
    - test -f $PREFIX/lib/libwebp.so
    - test -f $PREFIX/lib/libwebpmux.so
    - test -f $PREFIX/include/webp/decode.h
    - test -f $PREFIX/include/webp/encode.h
    - test -f $PREFIX/include/webp/types.h
about:
  description: 'WebP is a method of lossy and lossless compression that can be used
    on a

    large variety of photographic, translucent and graphical images found on the

    web. The degree of lossy compression is adjustable so a user can choose the

    trade-off between file size and image quality.

    libwebp-base provides the headers and shared libraries. For cwebp and dwep,

    binaries install libwebp.

    '
  dev_url: https://chromium.googlesource.com/webm/libwebp
  doc_url: https://developers.google.com/speed/webp/docs/using
  home: https://developers.google.com/speed/webp
  license: BSD-3-Clause
  license_file: COPYING
  summary: WebP image library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carterbox
    - dschreij
    - ocefpaf
