CI: azure
c_compiler: gcc
c_compiler_version: '9'
cdt_name: cos6
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
cxx_compiler_version: '9'
docker_image: quay.io/condaforge/linux-anvil-comp7
extend_keys:
- ignore_version
- ignore_build_only_deps
- pin_run_as_build
- extend_keys
fortran_compiler: gfortran
freetype: '2'
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.17'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  freetype:
    max_pin: x
  tk:
    max_pin: x.x
python: 3.8.* *_cpython
python_impl: cpython
r_base: '3.5'
target_platform: linux-64
tk: '8.6'
zip_keys:
- - python
  - numpy
  - python_impl
- - cdt_name
  - docker_image
- - c_compiler_version
  - cxx_compiler_version
