# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: matplotlib-base
  version: 3.4.1
source:
  patches: null
  sha256: e662bdde3f493b0f14f658095d91c36521d0f2d96c0a4b9fad55fca6d6300a87
  url: https://github.com/matplotlib/matplotlib/archive/v3.4.1.tar.gz
build:
  number: 0
  string: py38hcc49a3a_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - gcc_impl_linux-64 9.3.0 h70c0ae5_18
    - gcc_linux-64 9.3.0 hf25ea35_30
    - gxx_impl_linux-64 9.3.0 hd87eabc_18
    - gxx_linux-64 9.3.0 h3fbe746_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_18
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-devel_linux-64 9.3.0 hb016644_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 h77966d4_13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py38h578d9bd_1
    - cycler 0.10.0 py_2
    - freetype 2.10.4 h0708190_1
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libblas 3.9.0 8_openblas
    - libcblas 3.9.0 8_openblas
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgfortran-ng 9.3.0 hff62375_18
    - libgfortran5 9.3.0 hff62375_18
    - libgomp 9.3.0 h2828fa1_18
    - liblapack 3.9.0 8_openblas
    - libopenblas 0.3.12 pthreads_h4812303_1
    - libpng 1.6.37 h21135ba_2
    - libstdcxx-ng 9.3.0 h6de172a_18
    - ncurses 6.2 h58526e2_4
    - nose 1.3.7 py_1006
    - numpy 1.17.5 py38h18fd61f_1
    - openssl 1.1.1k h7f98852_0
    - pip 21.0.1 pyhd8ed1ab_0
    - pyparsing 2.4.7 pyh9f0ad1d_0
    - python 3.8.8 hffdb5ce_0_cpython
    - python-dateutil 2.8.1 py_0
    - python_abi 3.8 1_cp38
    - readline 8.0 he28a2e2_2
    - setuptools 49.6.0 py38h578d9bd_3
    - six 1.15.0 pyh9f0ad1d_0
    - sqlite 3.35.3 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - certifi >=2020.06.20
    - cycler >=0.10
    - freetype >=2.10.4,<3.0a0
    - freetype >=2.10.4,<3.0a0
    - kiwisolver >=1.0.1
    - libgcc-ng >=9.3.0
    - libstdcxx-ng >=9.3.0
    - numpy >=1.17.5,<2.0a0
    - pillow >=6.2.0
    - pyparsing >=2.2.1
    - python >=3.8,<3.9.0a0
    - python-dateutil >=2.1
    - python_abi 3.8.* *_cp38
    - setuptools
    - tk >=8.6.10,<8.7.0a0
    - tk >=8.6.10,<8.7.0a0
    - tornado
test:
  imports:
    - matplotlib
    - matplotlib._image
    - matplotlib._path
    - matplotlib._tri
    - matplotlib.backends._backend_agg
    - matplotlib.backends._tkagg
    - matplotlib.ft2font
    - matplotlib.pyplot
    - matplotlib.ttconv
    - mpl_toolkits
    - pylab
  requires:
    - pytest
about:
  description: 'matplotlib is a python 2D plotting library which produces publication

    quality figures in a variety of hardcopy formats and interactive

    environments across platforms. matplotlib can be used in Python scripts,

    the Python and IPython shell (ala MATLAB or Mathematica), web

    application servers, and six graphical user interface toolkits.

    '
  dev_url: https://github.com/matplotlib/matplotlib/
  doc_url: http://matplotlib.org/contents.html
  home: http://matplotlib.org/
  license: LicenseRef-PSF-based
  license_family: PSF
  license_file: LICENSE/LICENSE
  license_url: http://matplotlib.sourceforge.net/users/license.html
  summary: Publication quality figures in Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dopplershift
    - mdboom
    - ocefpaf
    - pelson
    - tacaswell
