# This file created by conda-build 3.18.10
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Oct 23 14:20:12 2019
# ------------------------------------------------

package:
    name: cycler
    version: 0.10.0
source:
    sha256: cd7b2d1018258d7247a71425e9f26463dfb444d411c39569972f4ce586b0c9d8
    url: https://pypi.io/packages/source/c/cycler/cycler-0.10.0.tar.gz
build:
    noarch: python
    number: '2'
    script: /home/conda/feedstock_root/build_artifacts/cycler_1571840491688/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
        -m pip install . --no-deps -vv
    string: py_2
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2019.9.11 hecc5488_0
        - certifi 2019.9.11 py27_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - pip 19.3.1 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - setuptools 41.4.0 py27_0
        - six 1.12.0 py27_1000
        - sqlite 3.30.1 hcee41ef_0
        - tk 8.6.9 hed695b0_1003
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h516909a_1006
    run:
        - python
        - six
test:
    imports:
        - cycler
about:
    home: http://github.com/matplotlib/cycler
    license: BSD-3-Clause
    license_file: LICENSE
    summary: Composable style cycles
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jankatins
        - ocefpaf
        - pelson
        - tacaswell
