# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Jan  8 09:55:17 2021
# ------------------------------------------------

package:
    name: kiwisolver
    version: 1.3.1
source:
    sha256: 950a199911a8d94683a6b10321f9345d5a3a8433ec58b217ace979e18f16e248
    url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-1.3.1.tar.gz
build:
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/kiwisolver_1610099769230/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
        -m pip install . -vv
    string: py38h1fd1430_1
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35.1 h193b22a_1
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 9.3.0 h28f5a38_17
        - gcc_linux-64 9.3.0 h7247604_29
        - gxx_impl_linux-64 9.3.0 h53cdd4c_17
        - gxx_linux-64 9.3.0 h0d07fa4_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35.1 hea4e1c9_1
        - libgcc-devel_linux-64 9.3.0 hfd08b2a_17
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-devel_linux-64 9.3.0 h4084dd6_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.12.5 ha878542_0
        - certifi 2020.12.5 py38h578d9bd_1
        - cppy 1.1.0 pyh9f0ad1d_0
        - ld_impl_linux-64 2.35.1 hea4e1c9_1
        - libffi 3.3 h58526e2_2
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 h58526e2_4
        - openssl 1.1.1i h7f98852_0
        - pip 20.3.3 pyhd8ed1ab_0
        - python 3.8.6 hffdb5ce_4_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py38h578d9bd_3
        - sqlite 3.34.0 h74cdb3f_0
        - tk 8.6.10 h21135ba_1
        - wheel 0.36.2 pyhd3deb0d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - libgcc-ng >=9.3.0
        - libstdcxx-ng >=9.3.0
        - python >=3.8,<3.9.0a0
        - python_abi 3.8.* *_cp38
test:
    commands:
        - pip check
    imports:
        - kiwisolver
    requires:
        - pip
about:
    home: https://github.com/nucleic/kiwi
    license: BSD-3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: A fast implementation of the Cassowary constraint solver
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - MatthieuDartiailh
        - blink1073
        - ericdill
        - licode
        - ocefpaf
        - sccolbert
        - tacaswell
