# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Feb 12 12:04:42 2021
# ------------------------------------------------

package:
  name: proj
  version: 7.2.0
source:
  sha256: 2957798e5fe295ff96a2af1889d0428e486363d210889422f76dd744f7885763
  url: http://download.osgeo.org/proj/proj-7.2.0.tar.gz
build:
  number: '2'
  run_exports:
    - proj >=7.2.0,<7.2.1.0a0
  string: h277dcde_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - autoconf 2.69 pl5320h36c2ea0_10
    - automake 1.16.2 pl5320ha770c72_3
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 hc3fd857_29
    - gcc_impl_linux-64 9.3.0 h70c0ae5_18
    - gcc_linux-64 9.3.0 h7247604_29
    - gnuconfig 2020.11.07 hd8ed1ab_0
    - gxx_impl_linux-64 9.3.0 hd87eabc_18
    - gxx_linux-64 9.3.0 h0d07fa4_29
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_18
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-devel_linux-64 9.3.0 hb016644_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - libtool 2.4.6 h58526e2_1007
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.0 h36c2ea0_0
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 h77966d4_13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - c-ares 1.17.1 h36c2ea0_0
    - ca-certificates 2020.12.5 ha878542_0
    - jpeg 9d h36c2ea0_0
    - krb5 1.17.2 h926e7f8_0
    - libcurl 7.71.1 hcdd3856_8
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libnghttp2 1.43.0 h812cca2_0
    - libssh2 1.9.0 hab1572f_5
    - libstdcxx-ng 9.3.0 h6de172a_18
    - libtiff 4.2.0 hdc55705_0
    - libwebp-base 1.2.0 h7f98852_0
    - lz4-c 1.9.3 h9c3ff4c_0
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1i h7f98852_0
    - readline 8.0 he28a2e2_2
    - sqlite 3.34.0 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
    - zstd 1.4.8 ha95c52a_1
  run:
    - libcurl >=7.71.1,<8.0a0
    - libcurl >=7.71.1,<8.0a0
    - libgcc-ng >=9.3.0
    - libstdcxx-ng >=9.3.0
    - libtiff >=4.2.0,<5.0a0
    - libtiff >=4.2.0,<5.0a0
    - sqlite >=3.34.0,<4.0a0
    - sqlite >=3.34.0,<4.0a0
  run_constrained:
    - proj4 ==999999999999
test:
  commands:
    - test -f ${PREFIX}/lib/libproj${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libproj.a
    - echo -105 40 | proj +proj=utm +zone=13 +ellps=WGS84
    - echo -117 30 | cs2cs +proj=latlong +datum=NAD27 +to +proj=latlong +datum=NAD83
    - echo -105 40 | cs2cs +init=epsg:4326 +to +init=epsg:2975
about:
  home: https://proj.org/
  license: MIT
  license_file: COPYING
  summary: Cartographic Projections and Coordinate Transformations Library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - hobu
    - msarahan
    - mwtoews
    - ocefpaf
    - pelson
    - snowman2
    - xylar
