# This file created by conda-build 3.21.3
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jan 14 17:53:06 2021
# ------------------------------------------------

package:
  name: freetype
  version: 2.10.4
source:
  patches:
    - 0003-Install-the-pkg-config-file-on-Windows-too.patch
  sha256: 5eab795ebb23ac77001cfb68b7d4d50b5d6c7469247b0b01b2c953269f658dac
  url: http://download.savannah.gnu.org/releases/freetype/freetype-2.10.4.tar.gz
build:
  number: '1'
  run_exports:
    - freetype >=2.10.4,<3.0a0
  string: h0708190_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_1
    - binutils_linux-64 2.35 hc3fd857_29
    - gcc_impl_linux-64 9.3.0 h28f5a38_17
    - gcc_linux-64 9.3.0 h7247604_29
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_1
    - libgcc-devel_linux-64 9.3.0 hfd08b2a_17
    - libgcc-ng 9.3.0 h5dbcf3e_17
    - libgomp 9.3.0 h5dbcf3e_17
    - libstdcxx-ng 9.3.0 h2ae2ef3_17
    - libtool 2.4.6 h58526e2_1007
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 h77966d4_13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h5dbcf3e_17
    - libgomp 9.3.0 h5dbcf3e_17
    - libpng 1.6.37 h21135ba_2
    - zlib 1.2.11 h516909a_1010
  run:
    - libgcc-ng >=9.3.0
    - libpng >=1.6.37,<1.7.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - ${PREFIX}/bin/freetype-config --version
about:
  description: 'FreeType is designed to be small, efficient, highly customizable

    and portable while capable of producing high-quality output (glyph images)

    of most vector and bitmap font formats.

    '
  dev_url: http://git.savannah.gnu.org/cgit/freetype/
  doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
  doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
  home: https://www.freetype.org/
  license: GPL-2.0-only and LicenseRef-FreeType
  license_file:
    - docs/FTL.TXT
    - docs/GPLv2.TXT
  summary: A Free, High-Quality, and Portable Font Engine
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
