CI: azure
c_compiler: gcc
c_compiler_version: '9'
cdt_name: cos6
channel_sources: conda-forge,defaults
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
docker_image: quay.io/condaforge/linux-anvil-comp7
extend_keys:
- ignore_build_only_deps
- extend_keys
- pin_run_as_build
- ignore_version
fortran_compiler: gfortran
freetype: '2'
ignore_build_only_deps:
- python
- numpy
jpeg: '9'
libtiff: '4'
lua: '5'
numpy: '1.16'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
  freetype:
    max_pin: x
  jpeg:
    max_pin: x
  libtiff:
    max_pin: x
  tk:
    max_pin: x.x
  zlib:
    max_pin: x.x
python: 3.8.* *_cpython
r_base: '3.5'
target_platform: linux-64
tk: '8.6'
zip_keys:
- - cdt_name
  - docker_image
zlib: '1.2'
