# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Apr  7 17:53:36 2021
# ------------------------------------------------

package:
  name: pillow
  version: 8.1.2
source:
  sha256: b07c660e014852d98a00a91adfbe25033898a9d90a8f39beb2437d22a203fc44
  url: https://pypi.io/packages/source/P/Pillow/Pillow-8.1.2.tar.gz
build:
  number: '1'
  string: py38ha0e1e83_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - gcc_impl_linux-64 9.3.0 h70c0ae5_18
    - gcc_linux-64 9.3.0 hf25ea35_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_18
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - sysroot_linux-64 2.12 h77966d4_13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py38h578d9bd_1
    - freetype 2.10.4 h0708190_1
    - jpeg 9d h36c2ea0_0
    - lcms2 2.12 hddcbb42_0
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libpng 1.6.37 h21135ba_2
    - libstdcxx-ng 9.3.0 h6de172a_18
    - libtiff 4.2.0 hdc55705_0
    - libwebp-base 1.2.0 h7f98852_2
    - lz4-c 1.9.3 h9c3ff4c_0
    - ncurses 6.2 h58526e2_4
    - openjpeg 2.4.0 hf7af979_0
    - openssl 1.1.1k h7f98852_0
    - pip 21.0.1 pyhd8ed1ab_0
    - python 3.8.8 hffdb5ce_0_cpython
    - python_abi 3.8 1_cp38
    - readline 8.0 he28a2e2_2
    - setuptools 49.6.0 py38h578d9bd_3
    - sqlite 3.35.4 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
    - zstd 1.4.9 ha95c52a_0
  run:
    - freetype >=2.10.4,<3.0a0
    - freetype >=2.10.4,<3.0a0
    - jpeg >=9d,<10a
    - jpeg >=9d,<10a
    - lcms2 >=2.12,<3.0a0
    - libgcc-ng >=9.3.0
    - libtiff >=4.2.0,<5.0a0
    - libtiff >=4.2.0,<5.0a0
    - olefile
    - openjpeg >=2.4.0,<3.0a0
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - tk >=8.6.10,<8.7.0a0
    - tk >=8.6.10,<8.7.0a0
    - zlib >=1.2.11,<1.3.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  imports:
    - PIL
    - PIL.Image
    - PIL.ImageCms
  requires:
    - aiohttp
    - fsspec
    - requests
about:
  home: https://pillow.readthedocs.io
  license: LicenseRef-PIL
  license_file: LICENSE
  summary: Pillow is the friendly PIL fork by Alex Clark and Contributors
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - patricksnape
    - pelson
