# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Dec 28 23:17:10 2020
# ------------------------------------------------

package:
    name: openjpeg
    version: 2.4.0
source:
    sha256: 8702ba68b442657f11aaeb2b338443ca8d5fb95b0d845757968a7be31ef7f16d
    url: https://github.com/uclouvain/openjpeg/archive/v2.4.0.tar.gz
build:
    number: '0'
    run_exports:
        - openjpeg >=2.4.0,<3.0a0
    string: hf7af979_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35.1 h193b22a_1
        - binutils_linux-64 2.35 hc3fd857_29
        - bzip2 1.0.8 h7f98852_4
        - c-ares 1.17.1 h36c2ea0_0
        - ca-certificates 2020.12.5 ha878542_0
        - cmake 3.19.2 h4547794_0
        - expat 2.2.9 he1b5a44_2
        - gcc_impl_linux-64 9.3.0 h28f5a38_17
        - gcc_linux-64 9.3.0 h7247604_29
        - gxx_impl_linux-64 9.3.0 h53cdd4c_17
        - gxx_linux-64 9.3.0 h0d07fa4_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - krb5 1.17.2 h926e7f8_0
        - ld_impl_linux-64 2.35.1 hea4e1c9_1
        - libcurl 7.71.1 hcdd3856_8
        - libedit 3.1.20191231 he28a2e2_2
        - libev 4.33 h516909a_1
        - libgcc-devel_linux-64 9.3.0 hfd08b2a_17
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libnghttp2 1.41.0 h8cfc5f6_2
        - libssh2 1.9.0 hab1572f_5
        - libstdcxx-devel_linux-64 9.3.0 h4084dd6_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - libuv 1.40.0 h7f98852_0
        - make 4.3 hd18ef5c_1
        - ncurses 6.2 h58526e2_4
        - openssl 1.1.1i h7f98852_0
        - rhash 1.3.6 h516909a_1001
        - sysroot_linux-64 2.12 h77966d4_13
        - tk 8.6.10 h21135ba_1
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - jpeg 9d h36c2ea0_0
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libpng 1.6.37 h21135ba_2
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - libtiff 4.1.0 h4f3a223_6
        - libwebp-base 1.1.0 h36c2ea0_3
        - lz4-c 1.9.2 he1b5a44_3
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
        - zstd 1.4.5 h6597ccf_2
    run:
        - libgcc-ng >=9.3.0
        - libpng >=1.6.37,<1.7.0a0
        - libpng >=1.6.37,<1.7.0a0
        - libstdcxx-ng >=9.3.0
        - libtiff >=4.1.0,<5.0a0
        - libtiff >=4.1.0,<5.0a0
        - zlib >=1.2.11,<1.3.0a0
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - opj_dump -i p0_01.j2k
    files:
        - p0_01.j2k
about:
    home: http://www.openjpeg.org/
    license: BSD-2-Clause
    license_file: LICENSE
    summary: An open-source JPEG 2000 codec written in C
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - gillins
        - mingwandroid
        - ocefpaf
